import type { Instrument, BlogPost } from './schema';

export const INITIAL_INSTRUMENTS: Array<Omit<Instrument, 'createdAt' | 'updatedAt'>> = [
  // METALS
  {
    id: 'XAU_USD',
    symbol: 'XAU/USD',
    displayName: 'Spot Gold / US Dollar',
    category: 'Metals',
    baseCurrency: 'XAU',
    quoteCurrency: 'USD',
    isActive: true,
    sortOrder: 1,
  },
  {
    id: 'XAG_USD',
    symbol: 'XAG/USD',
    displayName: 'Spot Silver / US Dollar',
    category: 'Metals',
    baseCurrency: 'XAG',
    quoteCurrency: 'USD',
    isActive: true,
    sortOrder: 2,
  },
  // ENERGY
  {
    id: 'WTI_USD',
    symbol: 'WTI/USD',
    displayName: 'WTI Crude Oil / US Dollar',
    category: 'Energy',
    baseCurrency: 'WTI',
    quoteCurrency: 'USD',
    isActive: true,
    sortOrder: 3,
  },
  {
    id: 'BRENT_USD',
    symbol: 'BRENT/USD',
    displayName: 'Brent Crude Oil / US Dollar',
    category: 'Energy',
    baseCurrency: 'BRENT',
    quoteCurrency: 'USD',
    isActive: true,
    sortOrder: 4,
  },
  // MAJOR FOREX
  {
    id: 'EUR_USD',
    symbol: 'EUR/USD',
    displayName: 'Euro / US Dollar',
    category: 'Forex',
    baseCurrency: 'EUR',
    quoteCurrency: 'USD',
    isActive: true,
    sortOrder: 5,
  },
  {
    id: 'GBP_USD',
    symbol: 'GBP/USD',
    displayName: 'British Pound / US Dollar',
    category: 'Forex',
    baseCurrency: 'GBP',
    quoteCurrency: 'USD',
    isActive: true,
    sortOrder: 6,
  },
  {
    id: 'USD_JPY',
    symbol: 'USD/JPY',
    displayName: 'US Dollar / Japanese Yen',
    category: 'Forex',
    baseCurrency: 'USD',
    quoteCurrency: 'JPY',
    isActive: true,
    sortOrder: 7,
  },
  {
    id: 'USD_CHF',
    symbol: 'USD/CHF',
    displayName: 'US Dollar / Swiss Franc',
    category: 'Forex',
    baseCurrency: 'USD',
    quoteCurrency: 'CHF',
    isActive: true,
    sortOrder: 8,
  },
  {
    id: 'AUD_USD',
    symbol: 'AUD/USD',
    displayName: 'Australian Dollar / US Dollar',
    category: 'Forex',
    baseCurrency: 'AUD',
    quoteCurrency: 'USD',
    isActive: true,
    sortOrder: 9,
  },
  {
    id: 'NZD_USD',
    symbol: 'NZD/USD',
    displayName: 'New Zealand Dollar / US Dollar',
    category: 'Forex',
    baseCurrency: 'NZD',
    quoteCurrency: 'USD',
    isActive: true,
    sortOrder: 10,
  },
  {
    id: 'USD_CAD',
    symbol: 'USD/CAD',
    displayName: 'US Dollar / Canadian Dollar',
    category: 'Forex',
    baseCurrency: 'USD',
    quoteCurrency: 'CAD',
    isActive: true,
    sortOrder: 11,
  },
  // CROSSES & EXOTICS
  {
    id: 'EUR_GBP',
    symbol: 'EUR/GBP',
    displayName: 'Euro / British Pound',
    category: 'Forex',
    baseCurrency: 'EUR',
    quoteCurrency: 'GBP',
    isActive: true,
    sortOrder: 12,
  },
  {
    id: 'EUR_JPY',
    symbol: 'EUR/JPY',
    displayName: 'Euro / Japanese Yen',
    category: 'Forex',
    baseCurrency: 'EUR',
    quoteCurrency: 'JPY',
    isActive: true,
    sortOrder: 13,
  },
  {
    id: 'GBP_JPY',
    symbol: 'GBP/JPY',
    displayName: 'British Pound / Japanese Yen',
    category: 'Forex',
    baseCurrency: 'GBP',
    quoteCurrency: 'JPY',
    isActive: true,
    sortOrder: 14,
  },
  {
    id: 'EUR_CHF',
    symbol: 'EUR/CHF',
    displayName: 'Euro / Swiss Franc',
    category: 'Forex',
    baseCurrency: 'EUR',
    quoteCurrency: 'CHF',
    isActive: true,
    sortOrder: 15,
  },
  {
    id: 'AUD_JPY',
    symbol: 'AUD/JPY',
    displayName: 'Australian Dollar / Japanese Yen',
    category: 'Forex',
    baseCurrency: 'AUD',
    quoteCurrency: 'JPY',
    isActive: true,
    sortOrder: 16,
  },
  {
    id: 'CAD_JPY',
    symbol: 'CAD/JPY',
    displayName: 'Canadian Dollar / Japanese Yen',
    category: 'Forex',
    baseCurrency: 'CAD',
    quoteCurrency: 'JPY',
    isActive: true,
    sortOrder: 17,
  },
  {
    id: 'NZD_JPY',
    symbol: 'NZD/JPY',
    displayName: 'New Zealand Dollar / Japanese Yen',
    category: 'Forex',
    baseCurrency: 'NZD',
    quoteCurrency: 'JPY',
    isActive: true,
    sortOrder: 18,
  },
  {
    id: 'USD_CNY',
    symbol: 'USD/CNY',
    displayName: 'US Dollar / Chinese Yuan',
    category: 'Forex',
    baseCurrency: 'USD',
    quoteCurrency: 'CNY',
    isActive: true,
    sortOrder: 19,
  },
  {
    id: 'USD_SGD',
    symbol: 'USD/SGD',
    displayName: 'US Dollar / Singapore Dollar',
    category: 'Forex',
    baseCurrency: 'USD',
    quoteCurrency: 'SGD',
    isActive: true,
    sortOrder: 20,
  },
  {
    id: 'USD_HKD',
    symbol: 'USD/HKD',
    displayName: 'US Dollar / Hong Kong Dollar',
    category: 'Forex',
    baseCurrency: 'USD',
    quoteCurrency: 'HKD',
    isActive: true,
    sortOrder: 21,
  },
  {
    id: 'USD_NOK',
    symbol: 'USD/NOK',
    displayName: 'US Dollar / Norwegian Krone',
    category: 'Forex',
    baseCurrency: 'USD',
    quoteCurrency: 'NOK',
    isActive: true,
    sortOrder: 22,
  },
  {
    id: 'USD_SEK',
    symbol: 'USD/SEK',
    displayName: 'US Dollar / Swedish Krona',
    category: 'Forex',
    baseCurrency: 'USD',
    quoteCurrency: 'SEK',
    isActive: true,
    sortOrder: 23,
  },
  {
    id: 'USD_TRY',
    symbol: 'USD/TRY',
    displayName: 'US Dollar / Turkish Lira',
    category: 'Forex',
    baseCurrency: 'USD',
    quoteCurrency: 'TRY',
    isActive: true,
    sortOrder: 24,
  },
  {
    id: 'USD_MXN',
    symbol: 'USD/MXN',
    displayName: 'US Dollar / Mexican Peso',
    category: 'Forex',
    baseCurrency: 'USD',
    quoteCurrency: 'MXN',
    isActive: true,
    sortOrder: 25,
  },
  {
    id: 'EUR_AUD',
    symbol: 'EUR/AUD',
    displayName: 'Euro / Australian Dollar',
    category: 'Forex',
    baseCurrency: 'EUR',
    quoteCurrency: 'AUD',
    isActive: true,
    sortOrder: 26,
  },
  {
    id: 'EUR_CAD',
    symbol: 'EUR/CAD',
    displayName: 'Euro / Canadian Dollar',
    category: 'Forex',
    baseCurrency: 'EUR',
    quoteCurrency: 'CAD',
    isActive: true,
    sortOrder: 27,
  },
  // CRYPTO
  {
    id: 'BTC_USD',
    symbol: 'BTC/USD',
    displayName: 'Bitcoin / US Dollar',
    category: 'Crypto',
    baseCurrency: 'BTC',
    quoteCurrency: 'USD',
    isActive: true,
    sortOrder: 28,
  },
];

export const INITIAL_BLOG_POSTS: Array<Omit<BlogPost, 'createdAt' | 'updatedAt'>> = [
  {
    id: 'blog-1',
    title: 'Navigating High-Impact CPI Prints: A Quantitative Framework for FX Traders',
    slug: 'navigating-high-impact-cpi-prints-fx-framework',
    excerpt:
      'Understanding why headline vs. core divergence drives sharp post-release repricing across dollar pairs, yields, and bullion.',
    contentMarkdown: `### The Mechanics of Inflation Surprises

When the US Consumer Price Index (CPI) crosses the tape, institutional desks do not react merely to the headline month-over-month number. The immediate order flow is governed by three interlinked vectors:

1. **The Core vs. Headline Spread**: Energy volatility frequently distorts headline numbers. Algorithmic execution engines dissect the core figure (excluding food and energy) to ascertain the underlying sticky momentum.
2. **Supercore Inflation (Services Ex-Shelter)**: Federal Reserve policymakers have repeatedly emphasized wage-sensitive non-housing services. A deceleration here signals genuine monetary transmission.
3. **Short-Dated Real Yield Movements**: The 2-year US Treasury yield adjusts within milliseconds. Gold (XAU/USD) and high-beta currencies (AUD/USD, GBP/USD) trade inversely to this instantaneous yield shock.

### Pre-Release Risk Management

Traders entering the 08:30 EST window must calculate spread widening and slippage buffers. During tier-one releases, liquidity providers widen spreads up to 5x standard quoting bounds. Executing limit orders rather than stop-market orders prevents toxic fills during the initial price discovery phase.`,
    coverImageUrl: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=1200&auto=format&fit=crop&q=80',
    authorName: 'Marcus Vance, Head of Macro Strategy',
    status: 'published',
    publishedAt: new Date('2026-10-01T12:00:00Z'),
    seoTitle: 'Navigating High-Impact CPI Prints | Forex Administrator Research',
    seoDescription:
      'A quantitative macro guide to trading US Consumer Price Index prints, yield adjustments, and gold volatility.',
  },
  {
    id: 'blog-2',
    title: 'Gold and Real Yields: Why XAU/USD Reacts to FOMC Projections',
    slug: 'gold-and-real-yields-fomc-reaction',
    excerpt:
      'Analyzing the structural relationship between Federal Reserve terminal rate expectations, TIPS yields, and precious metals positioning.',
    contentMarkdown: `### The Intrinsic Yield Disadvantage of Bullion

Gold generates zero nominal coupon. Consequently, its opportunity cost is represented by real yields specifically 10-year Treasury Inflation-Protected Securities (TIPS).

When the Federal Open Market Committee (FOMC) delivers an unexpected hawkish hold or upgrades its dot-plot trajectory, real rates jump. Gold instantly experiences algorithmic liquidation. Conversely, when economic event prints illustrate disinflation, downward real rate shifts unlock capital flows into bullion.

### Key Release Indicators to Monitor for Gold Traders

- **US Non-Farm Payrolls (NFP)**: Average Hourly Earnings dictate wage pressure assumptions.
- **US Core PCE Price Index**: The Fed's preferred inflation yardstick.
- **FOMC Statement & Press Conference**: Dot plot distribution and Chair forward guidance.`,
    coverImageUrl: 'https://images.unsplash.com/photo-1620321023374-d1a68fbc720d?w=1200&auto=format&fit=crop&q=80',
    authorName: 'Elena Rostova, Senior Commodities Analyst',
    status: 'published',
    publishedAt: new Date('2026-10-04T09:30:00Z'),
    seoTitle: 'Gold and Real Yields: FOMC Volatility Analysis | Forex Administrator',
    seoDescription:
      'In-depth institutional analysis of XAU/USD sensitivity to Fed dot-plots, TIPS real rates, and terminal fed funds expectations.',
  },
  {
    id: 'blog-3',
    title: 'Energy Market Shocks: Trading Crude Oil Ahead of OPEC+ and EIA Inventories',
    slug: 'energy-market-shocks-crude-oil-eia-inventories',
    excerpt:
      'A tactical guide to deciphering Wednesday EIA crude inventory releases, refinery runs, and geopolitical risk premiums on WTI and Brent.',
    contentMarkdown: `### Wednesday 10:30 AM EST: The Weekly EIA Pulse

The US Energy Information Administration (EIA) Weekly Petroleum Status Report remains the highest-velocity data event for crude oil traders. Key variables examined:

- **Commercial Crude Inventories**: Headline build or draw against expectations.
- **Strategic Petroleum Reserve (SPR) Flows**: Discerning whether government adjustments mask commercial demand changes.
- **Refinery Utilization Rates**: Gauging seasonal transitions and product demand (gasoline and distillates).
- **Implied Demand**: Weekly product supplied calculation.

When unexpected inventory builds materialize alongside softening gasoline demand, front-month futures experience sharp downward spikes that reverberate into CAD/USD and oil-sensitive currencies.`,
    coverImageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1200&auto=format&fit=crop&q=80',
    authorName: 'Liam Chen, Energy Strategist',
    status: 'published',
    publishedAt: new Date('2026-10-06T14:15:00Z'),
    seoTitle: 'Trading Crude Oil EIA Inventories & OPEC+ | Forex Administrator',
    seoDescription:
      'Mastering weekly EIA crude inventory data, refinery utilization, and global supply elasticity for WTI and Brent.',
  },
];

export const INITIAL_EVENTS = [
  // Previous releases (Oct 5-6)
  {
    id: 'evt-us-ism-mfg-oct',
    externalKey: 'finnhub_US_USD_ism_manufacturing_pmi_20261005',
    eventSeriesKey: 'US_ISM_MFG',
    eventName: 'ISM Manufacturing PMI',
    countryCode: 'US',
    currency: 'USD',
    impact: 'high',
    eventTimeUtc: new Date('2026-10-05T14:00:00Z'),
    isAllDay: false,
    actual: '49.2',
    forecast: '48.8',
    previous: '47.2',
    unit: '',
    source: 'Institute for Supply Management',
    rawData: {},
  },
  {
    id: 'evt-eu-retail-sales-oct',
    externalKey: 'finnhub_EU_EUR_retail_sales_mom_20261006',
    eventSeriesKey: 'EU_RETAIL_SALES',
    eventName: 'Eurozone Retail Sales m/m',
    countryCode: 'EU',
    currency: 'EUR',
    impact: 'medium',
    eventTimeUtc: new Date('2026-10-06T09:00:00Z'),
    isAllDay: false,
    actual: '0.2%',
    forecast: '0.1%',
    previous: '-0.3%',
    unit: '%',
    source: 'Eurostat',
    rawData: {},
  },
  {
    id: 'evt-au-rba-oct',
    externalKey: 'finnhub_AU_AUD_rba_rate_decision_20261006',
    eventSeriesKey: 'AU_RBA_RATE',
    eventName: 'RBA Cash Rate Target',
    countryCode: 'AU',
    currency: 'AUD',
    impact: 'high',
    eventTimeUtc: new Date('2026-10-06T03:30:00Z'),
    isAllDay: false,
    actual: '4.35%',
    forecast: '4.35%',
    previous: '4.35%',
    unit: '%',
    source: 'Reserve Bank of Australia',
    rawData: {},
  },
  // Today's releases (Oct 7)
  {
    id: 'evt-de-industrial-oct7',
    externalKey: 'finnhub_DE_EUR_german_industrial_production_20261007',
    eventSeriesKey: 'DE_IND_PROD',
    eventName: 'German Industrial Production m/m',
    countryCode: 'DE',
    currency: 'EUR',
    impact: 'medium',
    eventTimeUtc: new Date('2026-10-07T06:00:00Z'),
    isAllDay: false,
    actual: '0.8%',
    forecast: '0.5%',
    previous: '-1.4%',
    unit: '%',
    source: 'Federal Statistical Office Germany',
    rawData: {},
  },
  {
    id: 'evt-us-eia-crude-oct7',
    externalKey: 'finnhub_US_USD_eia_crude_oil_inventories_20261007',
    eventSeriesKey: 'US_EIA_CRUDE',
    eventName: 'EIA Weekly Crude Oil Stocks',
    countryCode: 'US',
    currency: 'USD',
    impact: 'high',
    eventTimeUtc: new Date('2026-10-07T14:30:00Z'),
    isAllDay: false,
    actual: null,
    forecast: '-1.25M',
    previous: '+3.89M',
    unit: 'Bbl',
    source: 'US Energy Information Administration',
    rawData: {},
  },
  {
    id: 'evt-us-fomc-minutes-oct7',
    externalKey: 'finnhub_US_USD_fomc_meeting_minutes_20261007',
    eventSeriesKey: 'US_FOMC_MINUTES',
    eventName: 'FOMC Meeting Minutes',
    countryCode: 'US',
    currency: 'USD',
    impact: 'high',
    eventTimeUtc: new Date('2026-10-07T18:00:00Z'),
    isAllDay: false,
    actual: null,
    forecast: null,
    previous: null,
    unit: '',
    source: 'Federal Reserve Board of Governors',
    rawData: {},
  },
  {
    id: 'evt-us-cpi-oct8',
    externalKey: 'finnhub_US_USD_cpi_mom_20261008',
    eventSeriesKey: 'US_CPI_MOM',
    eventName: 'US Consumer Price Index (CPI) m/m',
    countryCode: 'US',
    currency: 'USD',
    impact: 'high',
    eventTimeUtc: new Date('2026-10-08T12:30:00Z'),
    isAllDay: false,
    actual: null,
    forecast: '0.2%',
    previous: '0.3%',
    unit: '%',
    source: 'US Bureau of Labor Statistics',
    rawData: {},
  },
  {
    id: 'evt-us-core-cpi-oct8',
    externalKey: 'finnhub_US_USD_core_cpi_yoy_20261008',
    eventSeriesKey: 'US_CORE_CPI',
    eventName: 'US Core CPI y/y',
    countryCode: 'US',
    currency: 'USD',
    impact: 'high',
    eventTimeUtc: new Date('2026-10-08T12:30:00Z'),
    isAllDay: false,
    actual: null,
    forecast: '3.1%',
    previous: '3.2%',
    unit: '%',
    source: 'US Bureau of Labor Statistics',
    rawData: {},
  },
  {
    id: 'evt-us-initial-claims-oct8',
    externalKey: 'finnhub_US_USD_initial_jobless_claims_20261008',
    eventSeriesKey: 'US_JOBLESS_CLAIMS',
    eventName: 'Initial Jobless Claims',
    countryCode: 'US',
    currency: 'USD',
    impact: 'medium',
    eventTimeUtc: new Date('2026-10-08T12:30:00Z'),
    isAllDay: false,
    actual: null,
    forecast: '221K',
    previous: '225K',
    unit: '',
    source: 'US Department of Labor',
    rawData: {},
  },
  {
    id: 'evt-ca-employment-oct9',
    externalKey: 'finnhub_CA_CAD_employment_change_20261009',
    eventSeriesKey: 'CA_EMP_CHANGE',
    eventName: 'Canada Net Employment Change',
    countryCode: 'CA',
    currency: 'CAD',
    impact: 'high',
    eventTimeUtc: new Date('2026-10-09T12:30:00Z'),
    isAllDay: false,
    actual: null,
    forecast: '25.0K',
    previous: '22.1K',
    unit: '',
    source: 'Statistics Canada',
    rawData: {},
  },
  {
    id: 'evt-us-ppi-oct9',
    externalKey: 'finnhub_US_USD_producer_price_index_20261009',
    eventSeriesKey: 'US_PPI_FINAL',
    eventName: 'US Producer Price Index (PPI) m/m',
    countryCode: 'US',
    currency: 'USD',
    impact: 'medium',
    eventTimeUtc: new Date('2026-10-09T12:30:00Z'),
    isAllDay: false,
    actual: null,
    forecast: '0.1%',
    previous: '0.2%',
    unit: '%',
    source: 'US Bureau of Labor Statistics',
    rawData: {},
  },
  {
    id: 'evt-us-michigan-sent-oct9',
    externalKey: 'finnhub_US_USD_uom_consumer_sentiment_20261009',
    eventSeriesKey: 'US_UOM_SENTIMENT',
    eventName: 'Michigan Consumer Sentiment Prelim',
    countryCode: 'US',
    currency: 'USD',
    impact: 'medium',
    eventTimeUtc: new Date('2026-10-09T14:00:00Z'),
    isAllDay: false,
    actual: null,
    forecast: '70.8',
    previous: '70.1',
    unit: '',
    source: 'University of Michigan',
    rawData: {},
  },
  {
    id: 'evt-cn-trade-balance-oct10',
    externalKey: 'finnhub_CN_CNY_china_trade_balance_20261010',
    eventSeriesKey: 'CN_TRADE_BAL',
    eventName: 'China Trade Balance USD',
    countryCode: 'CN',
    currency: 'CNY',
    impact: 'medium',
    eventTimeUtc: new Date('2026-10-10T03:00:00Z'),
    isAllDay: false,
    actual: null,
    forecast: '88.5B',
    previous: '91.0B',
    unit: 'USD',
    source: 'General Administration of Customs',
    rawData: {},
  },
  {
    id: 'evt-uk-gdp-oct12',
    externalKey: 'finnhub_GB_GBP_uk_gdp_mom_20261012',
    eventSeriesKey: 'GB_GDP_MOM',
    eventName: 'UK Monthly GDP m/m',
    countryCode: 'GB',
    currency: 'GBP',
    impact: 'high',
    eventTimeUtc: new Date('2026-10-12T06:00:00Z'),
    isAllDay: false,
    actual: null,
    forecast: '0.2%',
    previous: '0.0%',
    unit: '%',
    source: 'Office for National Statistics',
    rawData: {},
  },
  {
    id: 'evt-eu-ecb-rate-oct15',
    externalKey: 'finnhub_EU_EUR_ecb_deposit_facility_rate_20261015',
    eventSeriesKey: 'EU_ECB_DEPOSIT_RATE',
    eventName: 'ECB Monetary Policy Decision',
    countryCode: 'EU',
    currency: 'EUR',
    impact: 'high',
    eventTimeUtc: new Date('2026-10-15T12:15:00Z'),
    isAllDay: false,
    actual: null,
    forecast: '3.25%',
    previous: '3.50%',
    unit: '%',
    source: 'European Central Bank',
    rawData: {},
  },
];
